add: file delete and svg compatibility
rero/flask-wiki pull request #10
Opened 2020-09-01 13:54 UTC by PascalRepond

closes #7 
adds possibility to delete files
extracts and update translations

2020-09-02 04:28 UTC, iGormilhit requested changes
Commit message proposition:

```
files: add file deletion & SVG support

* Closes #7 
```
On this project, the commit messages are not explicitly following the recommandations, but I think it's a good exercice to try to. See the commit template of `rero-ils`: https://github.com/rero/rero-ils/blob/dev/.gitmessage.txt

2020-09-02 06:01 UTC, jma requested changes

2020-09-02 06:01 UTC, jma commented on flask_wiki/templates/wiki/files.html
> +            <button data-toggle="modal" data-target=".deletemodal" class="btn btn-sm btn-outline-danger">
here I would use an id instead of a class as we want to target only one element in a page. `data-target="#deletemodal-filename"`

2020-09-02 06:01 UTC, jma commented on flask_wiki/templates/wiki/files.html
> +    <div class="modal fade deletemodal" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle"
here you can use a macro

2020-09-02 06:01 UTC, jma commented on flask_wiki/views.py
> +    print('asjdhaskj', url)
please remove this

2020-09-02 06:01 UTC, jma commented on flask_wiki/views.py
>      current_wiki.delete(url)
you can check the return value to change the flash message depending if the page has been removed or not.

2020-09-02 07:13 UTC, iGormilhit approved these changes

2020-09-02 07:29 UTC, PascalRepond commented on flask_wiki/templates/wiki/files.html
> +    <div class="modal fade deletemodal" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle"
I managed to do it with plain JS.

2020-09-03 05:41 UTC, jma requested changes

2020-09-03 05:41 UTC, jma commented on flask_wiki/templates/wiki/files.html
> +    function updateModal(e) {
This can't be in the page for security reason. You need to put it in a separate file.

2020-09-03 05:41 UTC, jma commented on flask_wiki/views.py
> +    except Exception as e:
this not work as no exception is raised. You need to check the return value.

2020-09-08 09:34 UTC, jma requested changes

2020-09-08 09:34 UTC, jma commented on flask_wiki/static/js/wiki.js
> +function updateModal(e) {
this should be in the document ready. I would change the name to be more specific. I would use jquery onclick instead.

2020-09-08 11:19 UTC, jma approved these changes

2020-09-08 11:19 UTC, jma commented on flask_wiki/views.py
> +    ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'svg'}
I would be great to have this as a flask-wiki configuration.

2020-09-08 11:59 UTC, merged