project: update dependencies
rero/flask-wiki pull request #59
Opened 2023-04-04 18:18 UTC by rerowep

* Uses flask_babel instead flask_babelex.

2023-04-05 05:00 UTC, Garfield-fr approved these changes

2023-04-05 05:44 UTC, PascalRepond requested changes
No pyproject change?
Tested and this doesn't work.

2023-04-11 05:53 UTC, PascalRepond approved these changes

2023-04-11 05:53 UTC, PascalRepond commented on examples/app.py
> +            'fr': 'Frensh',
French*

2023-04-27 06:13 UTC, jma requested changes

2023-04-27 06:13 UTC, jma commented on examples/app.py
> +    def get_locale():
Is `WIKI_LANGUAGES` not used anymore?

2023-04-27 06:13 UTC, jma commented on examples/data/files/.DS_Store
Please remove this and add this kind of files in the .gitignore.

2023-04-27 06:13 UTC, jma commented on flask_wiki/.DS_Store
Same here.

2023-04-27 06:13 UTC, jma commented on flask_wiki/templates/wiki/base.html
> +        {% for language in AVAILABLE_LANGUAGES.items() %}
Why not using `g`?

2023-04-27 06:13 UTC, jma commented on flask_wiki/translations/de/LC_MESSAGES/messages.mo
Please remove this from git and add a .gitignore.

2023-04-27 06:13 UTC, jma commented on flask_wiki/translations/hu/LC_MESSAGES/messages.po
Regenerate translations seems useless.

2023-05-02 05:19 UTC, rerowep commented on examples/app.py
> +    def get_locale():
I don't know, why do you ask?

2023-05-04 08:03 UTC, jma approved these changes

2023-07-06 12:26 UTC, merged